2024-08-21 13:14:22,408 INFO    StreamThr :68569 [internal.py:wandb_internal():85] W&B internal server running at pid: 68569, started at: 2024-08-21 13:14:22.408008
2024-08-21 13:14:22,409 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status
2024-08-21 13:14:22,419 INFO    WriterThread:68569 [datastore.py:open_for_write():87] open: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/run-5qgw4zu4.wandb
2024-08-21 13:14:22,421 DEBUG   SenderThread:68569 [sender.py:send():391] send: header
2024-08-21 13:14:22,441 DEBUG   SenderThread:68569 [sender.py:send():391] send: run
2024-08-21 13:14:23,133 INFO    SenderThread:68569 [dir_watcher.py:__init__():211] watching files in: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files
2024-08-21 13:14:23,133 INFO    SenderThread:68569 [sender.py:_start_run_threads():1200] run started: 5qgw4zu4 with start time 1724238862.407514
2024-08-21 13:14:23,139 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: check_version
2024-08-21 13:14:23,139 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: check_version
2024-08-21 13:14:23,197 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: run_start
2024-08-21 13:14:23,199 DEBUG   HandlerThread:68569 [system_info.py:__init__():26] System info init
2024-08-21 13:14:23,199 DEBUG   HandlerThread:68569 [system_info.py:__init__():41] System info init done
2024-08-21 13:14:23,199 INFO    HandlerThread:68569 [system_monitor.py:start():194] Starting system monitor
2024-08-21 13:14:23,199 INFO    SystemMonitor:68569 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-21 13:14:23,199 INFO    HandlerThread:68569 [system_monitor.py:probe():214] Collecting system info
2024-08-21 13:14:23,200 INFO    SystemMonitor:68569 [interfaces.py:start():188] Started cpu monitoring
2024-08-21 13:14:23,207 INFO    SystemMonitor:68569 [interfaces.py:start():188] Started disk monitoring
2024-08-21 13:14:23,210 INFO    SystemMonitor:68569 [interfaces.py:start():188] Started gpuapple monitoring
2024-08-21 13:14:23,211 INFO    SystemMonitor:68569 [interfaces.py:start():188] Started memory monitoring
2024-08-21 13:14:23,213 INFO    SystemMonitor:68569 [interfaces.py:start():188] Started network monitoring
2024-08-21 13:14:23,296 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:23,377 ERROR   HandlerThread:68569 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:23,377 DEBUG   HandlerThread:68569 [system_info.py:probe():152] Probing system
2024-08-21 13:14:23,378 DEBUG   HandlerThread:68569 [system_info.py:_probe_git():137] Probing git
2024-08-21 13:14:23,423 DEBUG   HandlerThread:68569 [system_info.py:_probe_git():145] Probing git done
2024-08-21 13:14:23,423 DEBUG   HandlerThread:68569 [system_info.py:probe():200] Probing system done
2024-08-21 13:14:23,423 DEBUG   HandlerThread:68569 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.11.5', 'heartbeatAt': '2024-08-21T11:14:23.377955', 'startedAt': '2024-08-21T11:14:22.404242', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/jackbmontgomery/deep-predictive-active-inference.git', 'commit': '1691130b1ebb3fdf0ed5eb01f8f3d39f97f44a07'}, 'email': 'jackbmontgomery2001@gmail.com', 'root': '/Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference', 'host': 'Jacks-MacBook-Pro-2.local', 'username': 'jackmontgomery', 'executable': '/Users/jackmontgomery/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 212.72167205810547}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-08-21 13:14:23,423 INFO    HandlerThread:68569 [system_monitor.py:probe():224] Finished collecting system info
2024-08-21 13:14:23,423 INFO    HandlerThread:68569 [system_monitor.py:probe():227] Publishing system info
2024-08-21 13:14:23,423 DEBUG   HandlerThread:68569 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-08-21 13:14:23,518 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:23,658 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:24,139 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/conda-environment.yaml
2024-08-21 13:14:25,401 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:25,628 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:26,836 DEBUG   HandlerThread:68569 [system_info.py:_save_conda():224] Saving conda packages done
2024-08-21 13:14:26,836 INFO    HandlerThread:68569 [system_monitor.py:probe():229] Finished publishing system info
2024-08-21 13:14:26,837 DEBUG   SenderThread:68569 [sender.py:send():391] send: files
2024-08-21 13:14:26,837 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-08-21 13:14:27,154 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/conda-environment.yaml
2024-08-21 13:14:27,154 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-metadata.json
2024-08-21 13:14:27,500 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:27,720 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:27,842 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:27,979 INFO    wandb-upload_0:68569 [upload_job.py:push():130] Uploaded file /var/folders/qc/h4k546bs6j9bl76bcjwyw5cw0000gn/T/tmpc1akgelrwandb/4sq3r0jg-wandb-metadata.json
2024-08-21 13:14:28,208 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: keepalive
2024-08-21 13:14:28,673 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:29,600 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:29,819 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:31,700 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:31,919 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:32,860 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:33,225 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: keepalive
2024-08-21 13:14:33,692 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:33,804 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:34,020 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:35,916 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:36,130 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:37,880 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:38,040 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:38,241 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: keepalive
2024-08-21 13:14:38,243 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:38,718 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:40,138 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:40,338 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:42,244 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:42,444 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:42,905 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:43,263 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: keepalive
2024-08-21 13:14:43,736 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:44,359 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:44,543 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:46,459 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:46,644 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:47,914 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:48,282 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: keepalive
2024-08-21 13:14:48,565 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:48,740 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:48,759 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:50,700 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:50,854 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:52,897 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:52,932 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:53,024 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:53,471 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: python_packages
2024-08-21 13:14:53,471 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: stop_status
2024-08-21 13:14:53,472 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:53,472 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: python_packages
2024-08-21 13:14:53,472 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: stop_status
2024-08-21 13:14:53,481 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,484 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,488 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,492 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,493 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,494 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,495 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,496 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,500 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,502 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,776 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:53,822 DEBUG   SenderThread:68569 [sender.py:send():391] send: telemetry
2024-08-21 13:14:53,822 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,823 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,823 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,823 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,823 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,823 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,824 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,824 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,824 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,824 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,824 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,825 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,825 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,825 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,825 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,825 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,826 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,826 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,826 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,826 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,826 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,826 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,826 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,826 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:53,829 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:53,830 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:53,830 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:53,830 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:54,126 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:54,126 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:54,127 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:54,127 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:54,249 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:14:54,249 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:14:54,249 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/requirements.txt
2024-08-21 13:14:54,476 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:54,538 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:54,538 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:54,538 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:54,539 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:54,793 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:54,793 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:54,793 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:54,794 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:55,013 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:55,117 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:55,119 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:55,119 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:55,120 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:55,136 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:55,254 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:14:55,480 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:55,678 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:55,678 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:55,679 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:55,679 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:55,989 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:55,990 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:55,990 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:55,990 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:56,177 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:14:56,177 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:14:56,177 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:14:56,178 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:14:56,260 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:14:56,260 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:14:56,481 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:57,123 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:57,253 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:57,484 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:58,182 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:58,266 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:14:58,489 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:14:58,796 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:14:59,229 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:59,366 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:14:59,490 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:00,492 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:01,331 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:01,490 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:01,494 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:02,496 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:03,446 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:03,476 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:03,501 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:03,590 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:03,818 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:04,214 DEBUG   SystemMonitor:68569 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-21 13:15:04,215 DEBUG   SenderThread:68569 [sender.py:send():391] send: telemetry
2024-08-21 13:15:04,215 DEBUG   SenderThread:68569 [sender.py:send():391] send: stats
2024-08-21 13:15:04,505 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:05,508 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:05,623 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:05,769 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:06,512 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:07,514 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:07,596 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: partial_history
2024-08-21 13:15:07,597 DEBUG   SenderThread:68569 [sender.py:send():391] send: history
2024-08-21 13:15:07,597 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: summary_record
2024-08-21 13:15:07,598 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:15:07,734 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:07,880 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:08,308 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:15:08,476 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: stop_status
2024-08-21 13:15:08,476 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: stop_status
2024-08-21 13:15:08,517 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:08,860 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:09,235 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:09,522 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:09,843 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:09,986 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:10,314 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:15:10,528 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:11,532 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:11,956 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:12,094 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:12,536 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:13,540 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:14,068 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:14,200 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:14,256 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:14,491 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:14,543 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:15,544 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:16,188 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:16,323 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:16,547 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:17,552 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:18,299 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:18,428 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:18,557 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:19,278 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:19,495 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:19,562 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:20,415 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:20,537 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:20,567 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:21,574 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:22,520 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:22,575 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:22,642 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:23,217 DEBUG   SystemMonitor:68569 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-21 13:15:23,217 DEBUG   SenderThread:68569 [sender.py:send():391] send: telemetry
2024-08-21 13:15:23,218 DEBUG   SenderThread:68569 [sender.py:send():391] send: stats
2024-08-21 13:15:23,481 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: stop_status
2024-08-21 13:15:23,481 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: stop_status
2024-08-21 13:15:23,577 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:24,294 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:24,581 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:24,625 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:24,755 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:24,838 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:25,380 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/config.yaml
2024-08-21 13:15:25,582 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:26,384 DEBUG   SenderThread:68569 [sender.py:send():391] send: telemetry
2024-08-21 13:15:26,384 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: server_info
2024-08-21 13:15:26,384 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: server_info
2024-08-21 13:15:26,660 DEBUG   SenderThread:68569 [sender.py:send():391] send: exit
2024-08-21 13:15:26,661 INFO    SenderThread:68569 [sender.py:send_exit():598] handling exit code: 0
2024-08-21 13:15:26,661 INFO    SenderThread:68569 [sender.py:send_exit():600] handling runtime: 63
2024-08-21 13:15:26,661 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:15:26,661 INFO    SenderThread:68569 [sender.py:send_exit():606] send defer
2024-08-21 13:15:26,661 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,662 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 0
2024-08-21 13:15:26,662 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,662 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 0
2024-08-21 13:15:26,662 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 1
2024-08-21 13:15:26,662 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,662 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 1
2024-08-21 13:15:26,662 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,662 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 1
2024-08-21 13:15:26,662 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 2
2024-08-21 13:15:26,662 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,662 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 2
2024-08-21 13:15:26,662 INFO    HandlerThread:68569 [system_monitor.py:finish():203] Stopping system monitor
2024-08-21 13:15:26,662 DEBUG   SystemMonitor:68569 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-21 13:15:26,662 DEBUG   SystemMonitor:68569 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-21 13:15:26,662 INFO    HandlerThread:68569 [interfaces.py:finish():200] Joined cpu monitor
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [interfaces.py:finish():200] Joined disk monitor
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [interfaces.py:finish():200] Joined gpuapple monitor
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [interfaces.py:finish():200] Joined memory monitor
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [interfaces.py:finish():200] Joined network monitor
2024-08-21 13:15:26,663 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 2
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 3
2024-08-21 13:15:26,663 DEBUG   SenderThread:68569 [sender.py:send():391] send: stats
2024-08-21 13:15:26,663 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 3
2024-08-21 13:15:26,663 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 3
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 4
2024-08-21 13:15:26,663 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,663 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 4
2024-08-21 13:15:26,663 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 4
2024-08-21 13:15:26,663 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 5
2024-08-21 13:15:26,663 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,664 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 5
2024-08-21 13:15:26,664 DEBUG   SenderThread:68569 [sender.py:send():391] send: summary
2024-08-21 13:15:26,664 INFO    SenderThread:68569 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-21 13:15:26,664 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,664 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 5
2024-08-21 13:15:26,664 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 6
2024-08-21 13:15:26,664 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:26,664 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 6
2024-08-21 13:15:26,664 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:26,664 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 6
2024-08-21 13:15:26,666 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:26,726 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:27,027 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 7
2024-08-21 13:15:27,028 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:27,028 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 7
2024-08-21 13:15:27,028 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:27,028 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 7
2024-08-21 13:15:27,383 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:15:27,384 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/config.yaml
2024-08-21 13:15:27,664 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: poll_exit
2024-08-21 13:15:27,893 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 8
2024-08-21 13:15:27,893 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: poll_exit
2024-08-21 13:15:27,893 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:27,893 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 8
2024-08-21 13:15:27,893 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:27,893 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 8
2024-08-21 13:15:27,893 INFO    SenderThread:68569 [job_builder.py:build():440] Attempting to build job artifact
2024-08-21 13:15:27,894 INFO    SenderThread:68569 [job_builder.py:_get_source_type():569] is repo sourced job
2024-08-21 13:15:27,894 INFO    SenderThread:68569 [job_builder.py:_get_program_relpath():587] run is notebook based run
2024-08-21 13:15:27,894 WARNING SenderThread:68569 [job_builder.py:_log_if_verbose():274] Source type is set to 'repo' but some required information is missing from the environment. A job will not be created from this run. See https://docs.wandb.ai/guides/launch/create-job
2024-08-21 13:15:27,894 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 9
2024-08-21 13:15:27,894 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:27,894 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 9
2024-08-21 13:15:27,894 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:27,894 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 9
2024-08-21 13:15:27,894 INFO    SenderThread:68569 [dir_watcher.py:finish():358] shutting down directory watcher
2024-08-21 13:15:28,386 INFO    Thread-36 :68569 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:15:28,387 INFO    SenderThread:68569 [dir_watcher.py:finish():388] scan: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files
2024-08-21 13:15:28,387 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/requirements.txt requirements.txt
2024-08-21 13:15:28,387 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log output.log
2024-08-21 13:15:28,389 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/config.yaml config.yaml
2024-08-21 13:15:28,391 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json wandb-summary.json
2024-08-21 13:15:28,393 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/conda-environment.yaml conda-environment.yaml
2024-08-21 13:15:28,396 INFO    SenderThread:68569 [dir_watcher.py:finish():402] scan save: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-metadata.json wandb-metadata.json
2024-08-21 13:15:28,398 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 10
2024-08-21 13:15:28,398 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:28,399 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 10
2024-08-21 13:15:28,400 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:28,400 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 10
2024-08-21 13:15:28,400 INFO    SenderThread:68569 [file_pusher.py:finish():169] shutting down file pusher
2024-08-21 13:15:28,669 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: poll_exit
2024-08-21 13:15:28,669 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: poll_exit
2024-08-21 13:15:28,841 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:29,099 INFO    wandb-upload_0:68569 [upload_job.py:push():130] Uploaded file /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/requirements.txt
2024-08-21 13:15:29,316 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: status_report
2024-08-21 13:15:29,501 INFO    wandb-upload_2:68569 [upload_job.py:push():130] Uploaded file /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/config.yaml
2024-08-21 13:15:29,502 INFO    wandb-upload_1:68569 [upload_job.py:push():130] Uploaded file /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/output.log
2024-08-21 13:15:29,513 INFO    wandb-upload_3:68569 [upload_job.py:push():130] Uploaded file /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/wandb-summary.json
2024-08-21 13:15:29,594 INFO    wandb-upload_4:68569 [upload_job.py:push():130] Uploaded file /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/files/conda-environment.yaml
2024-08-21 13:15:29,676 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: poll_exit
2024-08-21 13:15:29,677 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: poll_exit
2024-08-21 13:15:29,799 INFO    Thread-35 (_thread_body):68569 [sender.py:transition_state():626] send defer: 11
2024-08-21 13:15:29,800 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:29,800 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 11
2024-08-21 13:15:29,801 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:29,801 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 11
2024-08-21 13:15:29,801 INFO    SenderThread:68569 [file_pusher.py:join():175] waiting for file pusher
2024-08-21 13:15:29,802 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 12
2024-08-21 13:15:29,802 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:29,802 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 12
2024-08-21 13:15:29,802 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:29,802 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 12
2024-08-21 13:15:29,803 INFO    SenderThread:68569 [file_stream.py:finish():601] file stream finish called
2024-08-21 13:15:30,679 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: poll_exit
2024-08-21 13:15:30,714 INFO    SenderThread:68569 [file_stream.py:finish():605] file stream finish is done
2024-08-21 13:15:30,714 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 13
2024-08-21 13:15:30,714 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: poll_exit
2024-08-21 13:15:30,714 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:30,714 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 13
2024-08-21 13:15:30,715 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:30,715 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 13
2024-08-21 13:15:30,715 INFO    SenderThread:68569 [sender.py:transition_state():626] send defer: 14
2024-08-21 13:15:30,715 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: defer
2024-08-21 13:15:30,715 INFO    HandlerThread:68569 [handler.py:handle_request_defer():184] handle defer: 14
2024-08-21 13:15:30,715 DEBUG   SenderThread:68569 [sender.py:send():391] send: final
2024-08-21 13:15:30,715 DEBUG   SenderThread:68569 [sender.py:send():391] send: footer
2024-08-21 13:15:30,715 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: defer
2024-08-21 13:15:30,715 INFO    SenderThread:68569 [sender.py:send_request_defer():622] handle sender defer: 14
2024-08-21 13:15:30,716 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: poll_exit
2024-08-21 13:15:30,716 DEBUG   SenderThread:68569 [sender.py:send_request():418] send_request: poll_exit
2024-08-21 13:15:30,717 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-21 13:15:30,717 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: get_summary
2024-08-21 13:15:30,717 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: sampled_history
2024-08-21 13:15:30,718 DEBUG   HandlerThread:68569 [handler.py:handle_request():158] handle_request: shutdown
2024-08-21 13:15:30,718 INFO    HandlerThread:68569 [handler.py:finish():882] shutting down handler
2024-08-21 13:15:30,950 ERROR   gpuapple  :68569 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-21 13:15:31,720 INFO    SenderThread:68569 [sender.py:finish():1631] shutting down sender
2024-08-21 13:15:31,720 INFO    WriterThread:68569 [datastore.py:close():296] close: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240821_131422-5qgw4zu4/run-5qgw4zu4.wandb
2024-08-21 13:15:31,720 INFO    SenderThread:68569 [file_pusher.py:finish():169] shutting down file pusher
2024-08-21 13:15:31,720 INFO    SenderThread:68569 [file_pusher.py:join():175] waiting for file pusher
